# Generated by Django 4.1.3 on 2022-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElancoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsumedQuantity', models.IntegerField()),
                ('Cost', models.FloatField()),
                ('Date', models.DateField()),
                ('InstanceId', models.CharField(max_length=200)),
                ('MeterCategory', models.CharField(max_length=200)),
                ('ResourceGroup', models.CharField(max_length=200)),
                ('ResourceLocation', models.CharField(max_length=200)),
                ('Tags', models.JSONField()),
                ('UnitOfMeasure', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('ServiceName', models.CharField(max_length=200)),
            ],
        ),
    ]
