# Generated by Django 4.1.3 on 2022-11-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elancoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elancodata',
            name='ConsumedQuantity',
            field=models.FloatField(),
        ),
    ]
