# Generated by Django 4.1.3 on 2022-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elancoapi', '0002_alter_elancodata_consumedquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apiurl', models.CharField(max_length=200)),
            ],
        ),
    ]
