# Generated by Django 4.1.3 on 2022-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elancoapi', '0003_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resources',
            name='highestcost',
            field=models.FloatField(default=0),
        ),
    ]
